// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fastchain/mukade/models"
)

// GetCertificateOKCode is the HTTP code returned for type GetCertificateOK
const GetCertificateOKCode int = 200

/*
GetCertificateOK Successful retrieval of certificate data

swagger:response getCertificateOK
*/
type GetCertificateOK struct {

	/*
	  In: Body
	*/
	Payload *models.Certificate `json:"body,omitempty"`
}

// NewGetCertificateOK creates GetCertificateOK with default headers values
func NewGetCertificateOK() *GetCertificateOK {

	return &GetCertificateOK{}
}

// WithPayload adds the payload to the get certificate o k response
func (o *GetCertificateOK) WithPayload(payload *models.Certificate) *GetCertificateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get certificate o k response
func (o *GetCertificateOK) SetPayload(payload *models.Certificate) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCertificateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCertificateNotFoundCode is the HTTP code returned for type GetCertificateNotFound
const GetCertificateNotFoundCode int = 404

/*
GetCertificateNotFound Certificate not found

swagger:response getCertificateNotFound
*/
type GetCertificateNotFound struct {
}

// NewGetCertificateNotFound creates GetCertificateNotFound with default headers values
func NewGetCertificateNotFound() *GetCertificateNotFound {

	return &GetCertificateNotFound{}
}

// WriteResponse to the client
func (o *GetCertificateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetCertificateInternalServerErrorCode is the HTTP code returned for type GetCertificateInternalServerError
const GetCertificateInternalServerErrorCode int = 500

/*
GetCertificateInternalServerError Internal server error

swagger:response getCertificateInternalServerError
*/
type GetCertificateInternalServerError struct {
}

// NewGetCertificateInternalServerError creates GetCertificateInternalServerError with default headers values
func NewGetCertificateInternalServerError() *GetCertificateInternalServerError {

	return &GetCertificateInternalServerError{}
}

// WriteResponse to the client
func (o *GetCertificateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
