// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPFXOKCode is the HTTP code returned for type GetPFXOK
const GetPFXOKCode int = 200

/*
GetPFXOK Request processed

swagger:response getPFXOK
*/
type GetPFXOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetPFXOK creates GetPFXOK with default headers values
func NewGetPFXOK() *GetPFXOK {

	return &GetPFXOK{}
}

// WithPayload adds the payload to the get p f x o k response
func (o *GetPFXOK) WithPayload(payload io.ReadCloser) *GetPFXOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get p f x o k response
func (o *GetPFXOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPFXOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPFXNotFoundCode is the HTTP code returned for type GetPFXNotFound
const GetPFXNotFoundCode int = 404

/*
GetPFXNotFound Certificate not found

swagger:response getPFXNotFound
*/
type GetPFXNotFound struct {
}

// NewGetPFXNotFound creates GetPFXNotFound with default headers values
func NewGetPFXNotFound() *GetPFXNotFound {

	return &GetPFXNotFound{}
}

// WriteResponse to the client
func (o *GetPFXNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetPFXInternalServerErrorCode is the HTTP code returned for type GetPFXInternalServerError
const GetPFXInternalServerErrorCode int = 500

/*
GetPFXInternalServerError Internal server error

swagger:response getPFXInternalServerError
*/
type GetPFXInternalServerError struct {
}

// NewGetPFXInternalServerError creates GetPFXInternalServerError with default headers values
func NewGetPFXInternalServerError() *GetPFXInternalServerError {

	return &GetPFXInternalServerError{}
}

// WriteResponse to the client
func (o *GetPFXInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
