// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IssueCertificateHandlerFunc turns a function with the right signature into a issue certificate handler
type IssueCertificateHandlerFunc func(IssueCertificateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IssueCertificateHandlerFunc) Handle(params IssueCertificateParams) middleware.Responder {
	return fn(params)
}

// IssueCertificateHandler interface for that can handle valid issue certificate params
type IssueCertificateHandler interface {
	Handle(IssueCertificateParams) middleware.Responder
}

// NewIssueCertificate creates a new http.Handler for the issue certificate operation
func NewIssueCertificate(ctx *middleware.Context, handler IssueCertificateHandler) *IssueCertificate {
	return &IssueCertificate{Context: ctx, Handler: handler}
}

/*
	IssueCertificate swagger:route POST /certificates issueCertificate

# Issue a new certificate

Request the issuance of a new digital certificate.
*/
type IssueCertificate struct {
	Context *middleware.Context
	Handler IssueCertificateHandler
}

func (o *IssueCertificate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIssueCertificateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
