// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fastchain/mukade/models"
)

// RequestCertificateOKCode is the HTTP code returned for type RequestCertificateOK
const RequestCertificateOKCode int = 200

/*RequestCertificateOK Certificate requested successfully

swagger:response requestCertificateOK
*/
type RequestCertificateOK struct {

	/*
	  In: Body
	*/
	Payload *models.CertificateRequest `json:"body,omitempty"`
}

// NewRequestCertificateOK creates RequestCertificateOK with default headers values
func NewRequestCertificateOK() *RequestCertificateOK {

	return &RequestCertificateOK{}
}

// WithPayload adds the payload to the request certificate o k response
func (o *RequestCertificateOK) WithPayload(payload *models.CertificateRequest) *RequestCertificateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request certificate o k response
func (o *RequestCertificateOK) SetPayload(payload *models.CertificateRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestCertificateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RequestCertificateBadRequestCode is the HTTP code returned for type RequestCertificateBadRequest
const RequestCertificateBadRequestCode int = 400

/*RequestCertificateBadRequest Invalid request

swagger:response requestCertificateBadRequest
*/
type RequestCertificateBadRequest struct {
}

// NewRequestCertificateBadRequest creates RequestCertificateBadRequest with default headers values
func NewRequestCertificateBadRequest() *RequestCertificateBadRequest {

	return &RequestCertificateBadRequest{}
}

// WriteResponse to the client
func (o *RequestCertificateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RequestCertificateInternalServerErrorCode is the HTTP code returned for type RequestCertificateInternalServerError
const RequestCertificateInternalServerErrorCode int = 500

/*RequestCertificateInternalServerError Internal server error

swagger:response requestCertificateInternalServerError
*/
type RequestCertificateInternalServerError struct {
}

// NewRequestCertificateInternalServerError creates RequestCertificateInternalServerError with default headers values
func NewRequestCertificateInternalServerError() *RequestCertificateInternalServerError {

	return &RequestCertificateInternalServerError{}
}

// WriteResponse to the client
func (o *RequestCertificateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
