// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RequestCertificateHandlerFunc turns a function with the right signature into a request certificate handler
type RequestCertificateHandlerFunc func(RequestCertificateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RequestCertificateHandlerFunc) Handle(params RequestCertificateParams) middleware.Responder {
	return fn(params)
}

// RequestCertificateHandler interface for that can handle valid request certificate params
type RequestCertificateHandler interface {
	Handle(RequestCertificateParams) middleware.Responder
}

// NewRequestCertificate creates a new http.Handler for the request certificate operation
func NewRequestCertificate(ctx *middleware.Context, handler RequestCertificateHandler) *RequestCertificate {
	return &RequestCertificate{Context: ctx, Handler: handler}
}

/*
	RequestCertificate swagger:route POST /requests requestCertificate

# Request a new certificate

Request the issuance of a new digital certificate.
*/
type RequestCertificate struct {
	Context *middleware.Context
	Handler RequestCertificateHandler
}

func (o *RequestCertificate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRequestCertificateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
