// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RevokeCertificateOKCode is the HTTP code returned for type RevokeCertificateOK
const RevokeCertificateOKCode int = 200

/*
RevokeCertificateOK Certificate revoked successfully

swagger:response revokeCertificateOK
*/
type RevokeCertificateOK struct {
}

// NewRevokeCertificateOK creates RevokeCertificateOK with default headers values
func NewRevokeCertificateOK() *RevokeCertificateOK {

	return &RevokeCertificateOK{}
}

// WriteResponse to the client
func (o *RevokeCertificateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RevokeCertificateNotFoundCode is the HTTP code returned for type RevokeCertificateNotFound
const RevokeCertificateNotFoundCode int = 404

/*
RevokeCertificateNotFound Certificate not found

swagger:response revokeCertificateNotFound
*/
type RevokeCertificateNotFound struct {
}

// NewRevokeCertificateNotFound creates RevokeCertificateNotFound with default headers values
func NewRevokeCertificateNotFound() *RevokeCertificateNotFound {

	return &RevokeCertificateNotFound{}
}

// WriteResponse to the client
func (o *RevokeCertificateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// RevokeCertificateInternalServerErrorCode is the HTTP code returned for type RevokeCertificateInternalServerError
const RevokeCertificateInternalServerErrorCode int = 500

/*
RevokeCertificateInternalServerError Internal server error

swagger:response revokeCertificateInternalServerError
*/
type RevokeCertificateInternalServerError struct {
}

// NewRevokeCertificateInternalServerError creates RevokeCertificateInternalServerError with default headers values
func NewRevokeCertificateInternalServerError() *RevokeCertificateInternalServerError {

	return &RevokeCertificateInternalServerError{}
}

// WriteResponse to the client
func (o *RevokeCertificateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
