// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewRevokeCertificateParams creates a new RevokeCertificateParams object
//
// There are no default values defined in the spec.
func NewRevokeCertificateParams() RevokeCertificateParams {

	return RevokeCertificateParams{}
}

// RevokeCertificateParams contains all the bound params for the revoke certificate operation
// typically these are obtained from a http.Request
//
// swagger:parameters revokeCertificate
type RevokeCertificateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	CertificateID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRevokeCertificateParams() beforehand.
func (o *RevokeCertificateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCertificateID, rhkCertificateID, _ := route.Params.GetOK("certificateId")
	if err := o.bindCertificateID(rCertificateID, rhkCertificateID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCertificateID binds and validates parameter CertificateID from path.
func (o *RevokeCertificateParams) bindCertificateID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.CertificateID = raw

	return nil
}
