// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewSignRequestParams creates a new SignRequestParams object
// no default values defined in spec.
func NewSignRequestParams() SignRequestParams {

	return SignRequestParams{}
}

// SignRequestParams contains all the bound params for the sign request operation
// typically these are obtained from a http.Request
//
// swagger:parameters signRequest
type SignRequestParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	RequestID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSignRequestParams() beforehand.
func (o *SignRequestParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRequestID, rhkRequestID, _ := route.Params.GetOK("requestId")
	if err := o.bindRequestID(rRequestID, rhkRequestID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRequestID binds and validates parameter RequestID from path.
func (o *SignRequestParams) bindRequestID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.RequestID = raw

	return nil
}
