// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SignRequestOKCode is the HTTP code returned for type SignRequestOK
const SignRequestOKCode int = 200

/*SignRequestOK Request processed

swagger:response signRequestOK
*/
type SignRequestOK struct {
}

// NewSignRequestOK creates SignRequestOK with default headers values
func NewSignRequestOK() *SignRequestOK {

	return &SignRequestOK{}
}

// WriteResponse to the client
func (o *SignRequestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SignRequestBadRequestCode is the HTTP code returned for type SignRequestBadRequest
const SignRequestBadRequestCode int = 400

/*SignRequestBadRequest Invalid request

swagger:response signRequestBadRequest
*/
type SignRequestBadRequest struct {
}

// NewSignRequestBadRequest creates SignRequestBadRequest with default headers values
func NewSignRequestBadRequest() *SignRequestBadRequest {

	return &SignRequestBadRequest{}
}

// WriteResponse to the client
func (o *SignRequestBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SignRequestInternalServerErrorCode is the HTTP code returned for type SignRequestInternalServerError
const SignRequestInternalServerErrorCode int = 500

/*SignRequestInternalServerError Internal server error

swagger:response signRequestInternalServerError
*/
type SignRequestInternalServerError struct {
}

// NewSignRequestInternalServerError creates SignRequestInternalServerError with default headers values
func NewSignRequestInternalServerError() *SignRequestInternalServerError {

	return &SignRequestInternalServerError{}
}

// WriteResponse to the client
func (o *SignRequestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
