// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Certificate Authority API
//
//  API for managing digital certificates issued by a Certificate Authority (CA).
//  Schemes:
//    http
//  Host: ca.example.com
//  BasePath: /api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
