// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fastchain/mukade/models"
)

// IssueCertificateReader is a Reader for the IssueCertificate structure.
type IssueCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IssueCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIssueCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIssueCertificateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewIssueCertificateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /certificates] issueCertificate", response, response.Code())
	}
}

// NewIssueCertificateOK creates a IssueCertificateOK with default headers values
func NewIssueCertificateOK() *IssueCertificateOK {
	return &IssueCertificateOK{}
}

/*
IssueCertificateOK describes a response with status code 200, with default header values.

Certificate issued successfully
*/
type IssueCertificateOK struct {
	Payload *models.Certificate
}

// IsSuccess returns true when this issue certificate o k response has a 2xx status code
func (o *IssueCertificateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this issue certificate o k response has a 3xx status code
func (o *IssueCertificateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this issue certificate o k response has a 4xx status code
func (o *IssueCertificateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this issue certificate o k response has a 5xx status code
func (o *IssueCertificateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this issue certificate o k response a status code equal to that given
func (o *IssueCertificateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the issue certificate o k response
func (o *IssueCertificateOK) Code() int {
	return 200
}

func (o *IssueCertificateOK) Error() string {
	return fmt.Sprintf("[POST /certificates][%d] issueCertificateOK  %+v", 200, o.Payload)
}

func (o *IssueCertificateOK) String() string {
	return fmt.Sprintf("[POST /certificates][%d] issueCertificateOK  %+v", 200, o.Payload)
}

func (o *IssueCertificateOK) GetPayload() *models.Certificate {
	return o.Payload
}

func (o *IssueCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Certificate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIssueCertificateBadRequest creates a IssueCertificateBadRequest with default headers values
func NewIssueCertificateBadRequest() *IssueCertificateBadRequest {
	return &IssueCertificateBadRequest{}
}

/*
IssueCertificateBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type IssueCertificateBadRequest struct {
}

// IsSuccess returns true when this issue certificate bad request response has a 2xx status code
func (o *IssueCertificateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this issue certificate bad request response has a 3xx status code
func (o *IssueCertificateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this issue certificate bad request response has a 4xx status code
func (o *IssueCertificateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this issue certificate bad request response has a 5xx status code
func (o *IssueCertificateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this issue certificate bad request response a status code equal to that given
func (o *IssueCertificateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the issue certificate bad request response
func (o *IssueCertificateBadRequest) Code() int {
	return 400
}

func (o *IssueCertificateBadRequest) Error() string {
	return fmt.Sprintf("[POST /certificates][%d] issueCertificateBadRequest ", 400)
}

func (o *IssueCertificateBadRequest) String() string {
	return fmt.Sprintf("[POST /certificates][%d] issueCertificateBadRequest ", 400)
}

func (o *IssueCertificateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIssueCertificateInternalServerError creates a IssueCertificateInternalServerError with default headers values
func NewIssueCertificateInternalServerError() *IssueCertificateInternalServerError {
	return &IssueCertificateInternalServerError{}
}

/*
IssueCertificateInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type IssueCertificateInternalServerError struct {
}

// IsSuccess returns true when this issue certificate internal server error response has a 2xx status code
func (o *IssueCertificateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this issue certificate internal server error response has a 3xx status code
func (o *IssueCertificateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this issue certificate internal server error response has a 4xx status code
func (o *IssueCertificateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this issue certificate internal server error response has a 5xx status code
func (o *IssueCertificateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this issue certificate internal server error response a status code equal to that given
func (o *IssueCertificateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the issue certificate internal server error response
func (o *IssueCertificateInternalServerError) Code() int {
	return 500
}

func (o *IssueCertificateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /certificates][%d] issueCertificateInternalServerError ", 500)
}

func (o *IssueCertificateInternalServerError) String() string {
	return fmt.Sprintf("[POST /certificates][%d] issueCertificateInternalServerError ", 500)
}

func (o *IssueCertificateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
