// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRequestCRLParams creates a new RequestCRLParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRequestCRLParams() *RequestCRLParams {
	return &RequestCRLParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRequestCRLParamsWithTimeout creates a new RequestCRLParams object
// with the ability to set a timeout on a request.
func NewRequestCRLParamsWithTimeout(timeout time.Duration) *RequestCRLParams {
	return &RequestCRLParams{
		timeout: timeout,
	}
}

// NewRequestCRLParamsWithContext creates a new RequestCRLParams object
// with the ability to set a context for a request.
func NewRequestCRLParamsWithContext(ctx context.Context) *RequestCRLParams {
	return &RequestCRLParams{
		Context: ctx,
	}
}

// NewRequestCRLParamsWithHTTPClient creates a new RequestCRLParams object
// with the ability to set a custom HTTPClient for a request.
func NewRequestCRLParamsWithHTTPClient(client *http.Client) *RequestCRLParams {
	return &RequestCRLParams{
		HTTPClient: client,
	}
}

/*
RequestCRLParams contains all the parameters to send to the API endpoint

	for the request c r l operation.

	Typically these are written to a http.Request.
*/
type RequestCRLParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the request c r l params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestCRLParams) WithDefaults() *RequestCRLParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the request c r l params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestCRLParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the request c r l params
func (o *RequestCRLParams) WithTimeout(timeout time.Duration) *RequestCRLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request c r l params
func (o *RequestCRLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request c r l params
func (o *RequestCRLParams) WithContext(ctx context.Context) *RequestCRLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request c r l params
func (o *RequestCRLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request c r l params
func (o *RequestCRLParams) WithHTTPClient(client *http.Client) *RequestCRLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request c r l params
func (o *RequestCRLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RequestCRLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
