// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RequestCRLReader is a Reader for the RequestCRL structure.
type RequestCRLReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *RequestCRLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRequestCRLOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRequestCRLBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRequestCRLInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRequestCRLOK creates a RequestCRLOK with default headers values
func NewRequestCRLOK(writer io.Writer) *RequestCRLOK {
	return &RequestCRLOK{
		Payload: writer,
	}
}

/*RequestCRLOK handles this case with default header values.

Request processed
*/
type RequestCRLOK struct {
	Payload io.Writer
}

func (o *RequestCRLOK) Error() string {
	return fmt.Sprintf("[GET /crl.crl][%d] requestCRLOK  %+v", 200, o.Payload)
}

func (o *RequestCRLOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *RequestCRLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRequestCRLBadRequest creates a RequestCRLBadRequest with default headers values
func NewRequestCRLBadRequest() *RequestCRLBadRequest {
	return &RequestCRLBadRequest{}
}

/*RequestCRLBadRequest handles this case with default header values.

Invalid request
*/
type RequestCRLBadRequest struct {
}

func (o *RequestCRLBadRequest) Error() string {
	return fmt.Sprintf("[GET /crl.crl][%d] requestCRLBadRequest ", 400)
}

func (o *RequestCRLBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRequestCRLInternalServerError creates a RequestCRLInternalServerError with default headers values
func NewRequestCRLInternalServerError() *RequestCRLInternalServerError {
	return &RequestCRLInternalServerError{}
}

/*RequestCRLInternalServerError handles this case with default header values.

Internal server error
*/
type RequestCRLInternalServerError struct {
}

func (o *RequestCRLInternalServerError) Error() string {
	return fmt.Sprintf("[GET /crl.crl][%d] requestCRLInternalServerError ", 500)
}

func (o *RequestCRLInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
