// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fastchain/mukade/models"
)

// RequestCertificateReader is a Reader for the RequestCertificate structure.
type RequestCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRequestCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRequestCertificateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRequestCertificateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /requests] requestCertificate", response, response.Code())
	}
}

// NewRequestCertificateOK creates a RequestCertificateOK with default headers values
func NewRequestCertificateOK() *RequestCertificateOK {
	return &RequestCertificateOK{}
}

/*
RequestCertificateOK describes a response with status code 200, with default header values.

Certificate requested successfully
*/
type RequestCertificateOK struct {
	Payload *models.CertificateRequest
}

// IsSuccess returns true when this request certificate o k response has a 2xx status code
func (o *RequestCertificateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this request certificate o k response has a 3xx status code
func (o *RequestCertificateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this request certificate o k response has a 4xx status code
func (o *RequestCertificateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this request certificate o k response has a 5xx status code
func (o *RequestCertificateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this request certificate o k response a status code equal to that given
func (o *RequestCertificateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the request certificate o k response
func (o *RequestCertificateOK) Code() int {
	return 200
}

func (o *RequestCertificateOK) Error() string {
	return fmt.Sprintf("[POST /requests][%d] requestCertificateOK  %+v", 200, o.Payload)
}

func (o *RequestCertificateOK) String() string {
	return fmt.Sprintf("[POST /requests][%d] requestCertificateOK  %+v", 200, o.Payload)
}

func (o *RequestCertificateOK) GetPayload() *models.CertificateRequest {
	return o.Payload
}

func (o *RequestCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CertificateRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRequestCertificateBadRequest creates a RequestCertificateBadRequest with default headers values
func NewRequestCertificateBadRequest() *RequestCertificateBadRequest {
	return &RequestCertificateBadRequest{}
}

/*
RequestCertificateBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type RequestCertificateBadRequest struct {
}

// IsSuccess returns true when this request certificate bad request response has a 2xx status code
func (o *RequestCertificateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this request certificate bad request response has a 3xx status code
func (o *RequestCertificateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this request certificate bad request response has a 4xx status code
func (o *RequestCertificateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this request certificate bad request response has a 5xx status code
func (o *RequestCertificateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this request certificate bad request response a status code equal to that given
func (o *RequestCertificateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the request certificate bad request response
func (o *RequestCertificateBadRequest) Code() int {
	return 400
}

func (o *RequestCertificateBadRequest) Error() string {
	return fmt.Sprintf("[POST /requests][%d] requestCertificateBadRequest ", 400)
}

func (o *RequestCertificateBadRequest) String() string {
	return fmt.Sprintf("[POST /requests][%d] requestCertificateBadRequest ", 400)
}

func (o *RequestCertificateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRequestCertificateInternalServerError creates a RequestCertificateInternalServerError with default headers values
func NewRequestCertificateInternalServerError() *RequestCertificateInternalServerError {
	return &RequestCertificateInternalServerError{}
}

/*
RequestCertificateInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type RequestCertificateInternalServerError struct {
}

// IsSuccess returns true when this request certificate internal server error response has a 2xx status code
func (o *RequestCertificateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this request certificate internal server error response has a 3xx status code
func (o *RequestCertificateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this request certificate internal server error response has a 4xx status code
func (o *RequestCertificateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this request certificate internal server error response has a 5xx status code
func (o *RequestCertificateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this request certificate internal server error response a status code equal to that given
func (o *RequestCertificateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the request certificate internal server error response
func (o *RequestCertificateInternalServerError) Code() int {
	return 500
}

func (o *RequestCertificateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /requests][%d] requestCertificateInternalServerError ", 500)
}

func (o *RequestCertificateInternalServerError) String() string {
	return fmt.Sprintf("[POST /requests][%d] requestCertificateInternalServerError ", 500)
}

func (o *RequestCertificateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
