// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RevokeCertificateReader is a Reader for the RevokeCertificate structure.
type RevokeCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevokeCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRevokeCertificateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokeCertificateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /certificates/{certificateId}] revokeCertificate", response, response.Code())
	}
}

// NewRevokeCertificateOK creates a RevokeCertificateOK with default headers values
func NewRevokeCertificateOK() *RevokeCertificateOK {
	return &RevokeCertificateOK{}
}

/*
RevokeCertificateOK describes a response with status code 200, with default header values.

Certificate revoked successfully
*/
type RevokeCertificateOK struct {
}

// IsSuccess returns true when this revoke certificate o k response has a 2xx status code
func (o *RevokeCertificateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this revoke certificate o k response has a 3xx status code
func (o *RevokeCertificateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke certificate o k response has a 4xx status code
func (o *RevokeCertificateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke certificate o k response has a 5xx status code
func (o *RevokeCertificateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke certificate o k response a status code equal to that given
func (o *RevokeCertificateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the revoke certificate o k response
func (o *RevokeCertificateOK) Code() int {
	return 200
}

func (o *RevokeCertificateOK) Error() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateOK ", 200)
}

func (o *RevokeCertificateOK) String() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateOK ", 200)
}

func (o *RevokeCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeCertificateNotFound creates a RevokeCertificateNotFound with default headers values
func NewRevokeCertificateNotFound() *RevokeCertificateNotFound {
	return &RevokeCertificateNotFound{}
}

/*
RevokeCertificateNotFound describes a response with status code 404, with default header values.

Certificate not found
*/
type RevokeCertificateNotFound struct {
}

// IsSuccess returns true when this revoke certificate not found response has a 2xx status code
func (o *RevokeCertificateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke certificate not found response has a 3xx status code
func (o *RevokeCertificateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke certificate not found response has a 4xx status code
func (o *RevokeCertificateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke certificate not found response has a 5xx status code
func (o *RevokeCertificateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke certificate not found response a status code equal to that given
func (o *RevokeCertificateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the revoke certificate not found response
func (o *RevokeCertificateNotFound) Code() int {
	return 404
}

func (o *RevokeCertificateNotFound) Error() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateNotFound ", 404)
}

func (o *RevokeCertificateNotFound) String() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateNotFound ", 404)
}

func (o *RevokeCertificateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeCertificateInternalServerError creates a RevokeCertificateInternalServerError with default headers values
func NewRevokeCertificateInternalServerError() *RevokeCertificateInternalServerError {
	return &RevokeCertificateInternalServerError{}
}

/*
RevokeCertificateInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type RevokeCertificateInternalServerError struct {
}

// IsSuccess returns true when this revoke certificate internal server error response has a 2xx status code
func (o *RevokeCertificateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke certificate internal server error response has a 3xx status code
func (o *RevokeCertificateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke certificate internal server error response has a 4xx status code
func (o *RevokeCertificateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke certificate internal server error response has a 5xx status code
func (o *RevokeCertificateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this revoke certificate internal server error response a status code equal to that given
func (o *RevokeCertificateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the revoke certificate internal server error response
func (o *RevokeCertificateInternalServerError) Code() int {
	return 500
}

func (o *RevokeCertificateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateInternalServerError ", 500)
}

func (o *RevokeCertificateInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateInternalServerError ", 500)
}

func (o *RevokeCertificateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
