// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RevokeCertificateReader is a Reader for the RevokeCertificate structure.
type RevokeCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevokeCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRevokeCertificateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokeCertificateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRevokeCertificateOK creates a RevokeCertificateOK with default headers values
func NewRevokeCertificateOK() *RevokeCertificateOK {
	return &RevokeCertificateOK{}
}

/*RevokeCertificateOK handles this case with default header values.

Certificate revoked successfully
*/
type RevokeCertificateOK struct {
}

func (o *RevokeCertificateOK) Error() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateOK ", 200)
}

func (o *RevokeCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeCertificateNotFound creates a RevokeCertificateNotFound with default headers values
func NewRevokeCertificateNotFound() *RevokeCertificateNotFound {
	return &RevokeCertificateNotFound{}
}

/*RevokeCertificateNotFound handles this case with default header values.

Certificate not found
*/
type RevokeCertificateNotFound struct {
}

func (o *RevokeCertificateNotFound) Error() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateNotFound ", 404)
}

func (o *RevokeCertificateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeCertificateInternalServerError creates a RevokeCertificateInternalServerError with default headers values
func NewRevokeCertificateInternalServerError() *RevokeCertificateInternalServerError {
	return &RevokeCertificateInternalServerError{}
}

/*RevokeCertificateInternalServerError handles this case with default header values.

Internal server error
*/
type RevokeCertificateInternalServerError struct {
}

func (o *RevokeCertificateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /certificates/{certificateId}][%d] revokeCertificateInternalServerError ", 500)
}

func (o *RevokeCertificateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
