// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSignRequestParams creates a new SignRequestParams object
// with the default values initialized.
func NewSignRequestParams() *SignRequestParams {
	var ()
	return &SignRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSignRequestParamsWithTimeout creates a new SignRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSignRequestParamsWithTimeout(timeout time.Duration) *SignRequestParams {
	var ()
	return &SignRequestParams{

		timeout: timeout,
	}
}

// NewSignRequestParamsWithContext creates a new SignRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewSignRequestParamsWithContext(ctx context.Context) *SignRequestParams {
	var ()
	return &SignRequestParams{

		Context: ctx,
	}
}

// NewSignRequestParamsWithHTTPClient creates a new SignRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSignRequestParamsWithHTTPClient(client *http.Client) *SignRequestParams {
	var ()
	return &SignRequestParams{
		HTTPClient: client,
	}
}

/*SignRequestParams contains all the parameters to send to the API endpoint
for the sign request operation typically these are written to a http.Request
*/
type SignRequestParams struct {

	/*RequestID*/
	RequestID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sign request params
func (o *SignRequestParams) WithTimeout(timeout time.Duration) *SignRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sign request params
func (o *SignRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sign request params
func (o *SignRequestParams) WithContext(ctx context.Context) *SignRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sign request params
func (o *SignRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sign request params
func (o *SignRequestParams) WithHTTPClient(client *http.Client) *SignRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sign request params
func (o *SignRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestID adds the requestID to the sign request params
func (o *SignRequestParams) WithRequestID(requestID string) *SignRequestParams {
	o.SetRequestID(requestID)
	return o
}

// SetRequestID adds the requestId to the sign request params
func (o *SignRequestParams) SetRequestID(requestID string) {
	o.RequestID = requestID
}

// WriteToRequest writes these params to a swagger request
func (o *SignRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param requestId
	if err := r.SetPathParam("requestId", o.RequestID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
