// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SignRequestReader is a Reader for the SignRequest structure.
type SignRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SignRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSignRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSignRequestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSignRequestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSignRequestOK creates a SignRequestOK with default headers values
func NewSignRequestOK() *SignRequestOK {
	return &SignRequestOK{}
}

/*SignRequestOK handles this case with default header values.

Request processed
*/
type SignRequestOK struct {
}

func (o *SignRequestOK) Error() string {
	return fmt.Sprintf("[GET /requests/{requestId}][%d] signRequestOK ", 200)
}

func (o *SignRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSignRequestBadRequest creates a SignRequestBadRequest with default headers values
func NewSignRequestBadRequest() *SignRequestBadRequest {
	return &SignRequestBadRequest{}
}

/*SignRequestBadRequest handles this case with default header values.

Invalid request
*/
type SignRequestBadRequest struct {
}

func (o *SignRequestBadRequest) Error() string {
	return fmt.Sprintf("[GET /requests/{requestId}][%d] signRequestBadRequest ", 400)
}

func (o *SignRequestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSignRequestInternalServerError creates a SignRequestInternalServerError with default headers values
func NewSignRequestInternalServerError() *SignRequestInternalServerError {
	return &SignRequestInternalServerError{}
}

/*SignRequestInternalServerError handles this case with default header values.

Internal server error
*/
type SignRequestInternalServerError struct {
}

func (o *SignRequestInternalServerError) Error() string {
	return fmt.Sprintf("[GET /requests/{requestId}][%d] signRequestInternalServerError ", 500)
}

func (o *SignRequestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
