// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CertificateRequest certificate request
//
// swagger:model CertificateRequest
type CertificateRequest struct {

	// CN for autoissuer
	// Required: true
	Cn *string `json:"cn"`

	// PubKey hash
	ID string `json:"id,omitempty"`

	// Public key to be associated with the certificate.
	PublicKey string `json:"publicKey,omitempty"`

	// Raw request as string
	Raw string `json:"raw,omitempty"`

	// Name of the entity requesting the certificate.
	Subject string `json:"subject,omitempty"`
}

// Validate validates this certificate request
func (m *CertificateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCn(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CertificateRequest) validateCn(formats strfmt.Registry) error {

	if err := validate.Required("cn", "body", m.Cn); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this certificate request based on context it is used
func (m *CertificateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CertificateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CertificateRequest) UnmarshalBinary(b []byte) error {
	var res CertificateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
